################################### English language #####################################
[en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 2
# copyright
copyright = "Designed By [Themefisher](https://themefisher.com/) & Developed By [Gethugothemes](https://gethugothemes.com/)"



################################### French language #####################################
[fr]
languageName = "Fr"
languageCode = "fr-fr"
contentDir = "content/french"
weight = 3
# copyright
copyright = "Conçu Par [Themefisher](https://themefisher.com/) & Développé Par [Gethugothemes](https://gethugothemes.com/)"

################################### Spanish language #####################################
[es]
languageName = "Es"
languageCode = "es-CR"
contentDir = "content/spanish"
weight = 1
# copyright
copyright = "Diseñado por [Themefisher](https://themefisher.com/) & Desarrollado por [Gethugothemes](https://gethugothemes.com/)"