#################### default parameters ################################
# favicon
favicon = "images/favicon.png"
# logo
logo = "images/logopthen.png"
# use `x` with logo_width, example: "100x"
logo_width = "90x"
# logo text will only show when logo is missing.
logo_text = "Pets to Home"
# image gallery shortcode
image_gallery = true

# footer information
footer_info = "Pets to Home es una marca de Aselogística, Sociedad Anónima<br>Alajuela, Costa Rica"

# contact form action
contact_form_action = "https://formspree.io/f/xgernlzd" # contact form works with https://formspree.io

# career form action
career_form_action = "#" # career form works with https://formspree.io

# custom script on header, example: custom_script= "<script>console.log(\"Hello World\")</script>" 
custom_script= "" 

# Main Sections
mainSections= ["blog"]

# contact information
[contact_info]
address = "Local #65 Centro de Comercio Internacional, Alajuela"
phone = ["(506) 8859 8455", "(506) 6294 4788", "(506) 4082 3331"]
email = ["info@petstohomecr.com"]

# imaging processing
[imaging]
# Default JPEG or WebP quality setting. Default is 100.
quality = 100

# Preloader
[preloader]
enable = true
preloader = "images/dog-preloader.gif" # use jpg, png, svg or gif format.

# Navigation button
[navigation_button]
enable = false
label = "Sign Up Now"
link = "signup/"

# seo meta data for OpenGraph / Twitter Card
[metadata]
keywords = ["pets to home", "pet", "international pet relocation", "pet movers", "mascota", "transporte internacional de mascotas", "worldwide pet relocation", "pets", "mascotas"]
description = "Pets to Home - worldwide pet relocation"
author = "PTH"
image = "images/og-image.jpg" # this image will be used as fallback if a page has no image of its own

# matomo tracking: see https://matomo.org/
[matomo]
enable = false
url = "" # your matomo url
id = "" # your matomo id

# baidu analytics: see https://tongji.baidu.com/
[baidu]
enable = false
analytics_id = "" # Your ID

# plausible analytics: see https://plausible.io/
[plausible]
enable = false
domain = "" # yourdomain.com

# counter analytics: see https://counter.dev/setup.html
[counter]
enable = false
username = "" # your username

# site verifications
[site_verification]
google = "" # Your verification code
bing = "" # Your verification code
baidu = "" # Your verification code
facebook = "" # Your verification code

# cookies
[cookies]
enable = false
expire_days = 2
content = "This site uses cookies. By continuing to use this website, you agree to their use."
button = "I Accept"

# call-to-action
[cta]
enable = true
title = "Helping teams in the world with focus"
content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi egestas <br> Werat viverra id et aliquet. vulputate egestas sollicitudin."
button = "Download The Theme"


############################# social site ########################
[[social]]
title = "PTH Facebook"
icon = "lab la-facebook-f" # https://icons8.com/line-awesome
link = "https://es-la.facebook.com/petstohomecr/"

[[social]]
title = "PTH Instagram"
icon = "lab la-instagram" # https://icons8.com/line-awesome
link = "https://www.instagram.com/petstohomecr/"

[[social]]
title = "TikTok"
icon = "lab la-tumblr" # https://icons8.com/line-awesome
link = "https://www.tiktok.com/@petstohomecr?_t=8kJsCDF1Bu1&_r=1"
